	CPU u0 (
		.clk_clk                  (<connected-to-clk_clk>),                  //      clk.clk
		.dac_rst_export           (<connected-to-dac_rst_export>),           //  dac_rst.export
		.epcs_dclk                (<connected-to-epcs_dclk>),                //     epcs.dclk
		.epcs_sce                 (<connected-to-epcs_sce>),                 //         .sce
		.epcs_sdo                 (<connected-to-epcs_sdo>),                 //         .sdo
		.epcs_data0               (<connected-to-epcs_data0>),               //         .data0
		.reset_reset_n            (<connected-to-reset_reset_n>),            //    reset.reset_n
		.sdram_addr               (<connected-to-sdram_addr>),               //    sdram.addr
		.sdram_ba                 (<connected-to-sdram_ba>),                 //         .ba
		.sdram_cas_n              (<connected-to-sdram_cas_n>),              //         .cas_n
		.sdram_cke                (<connected-to-sdram_cke>),                //         .cke
		.sdram_cs_n               (<connected-to-sdram_cs_n>),               //         .cs_n
		.sdram_dq                 (<connected-to-sdram_dq>),                 //         .dq
		.sdram_dqm                (<connected-to-sdram_dqm>),                //         .dqm
		.sdram_ras_n              (<connected-to-sdram_ras_n>),              //         .ras_n
		.sdram_we_n               (<connected-to-sdram_we_n>),               //         .we_n
		.spi_adc_MISO             (<connected-to-spi_adc_MISO>),             //  spi_adc.MISO
		.spi_adc_MOSI             (<connected-to-spi_adc_MOSI>),             //         .MOSI
		.spi_adc_SCLK             (<connected-to-spi_adc_SCLK>),             //         .SCLK
		.spi_adc_SS_n             (<connected-to-spi_adc_SS_n>),             //         .SS_n
		.spi_dac_MISO             (<connected-to-spi_dac_MISO>),             //  spi_dac.MISO
		.spi_dac_MOSI             (<connected-to-spi_dac_MOSI>),             //         .MOSI
		.spi_dac_SCLK             (<connected-to-spi_dac_SCLK>),             //         .SCLK
		.spi_dac_SS_n             (<connected-to-spi_dac_SS_n>),             //         .SS_n
		.sync_in_export           (<connected-to-sync_in_export>),           //  sync_in.export
		.uart_rxd                 (<connected-to-uart_rxd>),                 //     uart.rxd
		.uart_txd                 (<connected-to-uart_txd>),                 //         .txd
		.uart_dbg_rxd             (<connected-to-uart_dbg_rxd>),             // uart_dbg.rxd
		.uart_dbg_txd             (<connected-to-uart_dbg_txd>),             //         .txd
		.varset_1_i_var0          (<connected-to-varset_1_i_var0>),          // varset_1.i_var0
		.varset_1_i_var1          (<connected-to-varset_1_i_var1>),          //         .i_var1
		.varset_1_i_var2          (<connected-to-varset_1_i_var2>),          //         .i_var2
		.varset_1_i_var3          (<connected-to-varset_1_i_var3>),          //         .i_var3
		.varset_1_i_var4          (<connected-to-varset_1_i_var4>),          //         .i_var4
		.varset_1_i_var5          (<connected-to-varset_1_i_var5>),          //         .i_var5
		.varset_1_i_var6          (<connected-to-varset_1_i_var6>),          //         .i_var6
		.varset_1_i_var7          (<connected-to-varset_1_i_var7>),          //         .i_var7
		.varset_1_i_var8          (<connected-to-varset_1_i_var8>),          //         .i_var8
		.varset_1_i_var9          (<connected-to-varset_1_i_var9>),          //         .i_var9
		.varset_1_i_var10         (<connected-to-varset_1_i_var10>),         //         .i_var10
		.varset_1_i_var11         (<connected-to-varset_1_i_var11>),         //         .i_var11
		.varset_1_i_var12         (<connected-to-varset_1_i_var12>),         //         .i_var12
		.varset_1_i_var13         (<connected-to-varset_1_i_var13>),         //         .i_var13
		.varset_1_i_var14         (<connected-to-varset_1_i_var14>),         //         .i_var14
		.varset_1_i_var15         (<connected-to-varset_1_i_var15>),         //         .i_var15
		.varset_1_i_var16         (<connected-to-varset_1_i_var16>),         //         .i_var16
		.varset_1_i_var17         (<connected-to-varset_1_i_var17>),         //         .i_var17
		.varset_1_i_var18         (<connected-to-varset_1_i_var18>),         //         .i_var18
		.varset_1_i_var19         (<connected-to-varset_1_i_var19>),         //         .i_var19
		.varset_1_i_var20         (<connected-to-varset_1_i_var20>),         //         .i_var20
		.varset_1_i_var21         (<connected-to-varset_1_i_var21>),         //         .i_var21
		.varset_1_i_var22         (<connected-to-varset_1_i_var22>),         //         .i_var22
		.varset_1_i_var23         (<connected-to-varset_1_i_var23>),         //         .i_var23
		.varset_1_i_var24         (<connected-to-varset_1_i_var24>),         //         .i_var24
		.varset_1_i_var25         (<connected-to-varset_1_i_var25>),         //         .i_var25
		.varset_1_i_var26         (<connected-to-varset_1_i_var26>),         //         .i_var26
		.varset_1_i_var27         (<connected-to-varset_1_i_var27>),         //         .i_var27
		.varset_1_i_var28         (<connected-to-varset_1_i_var28>),         //         .i_var28
		.varset_1_i_var29         (<connected-to-varset_1_i_var29>),         //         .i_var29
		.varset_1_i_var30         (<connected-to-varset_1_i_var30>),         //         .i_var30
		.varset_1_i_var31         (<connected-to-varset_1_i_var31>),         //         .i_var31
		.varset_1_i_var32         (<connected-to-varset_1_i_var32>),         //         .i_var32
		.varset_1_i_var33         (<connected-to-varset_1_i_var33>),         //         .i_var33
		.varset_1_i_var34         (<connected-to-varset_1_i_var34>),         //         .i_var34
		.varset_1_i_var35         (<connected-to-varset_1_i_var35>),         //         .i_var35
		.varset_1_i_var36         (<connected-to-varset_1_i_var36>),         //         .i_var36
		.varset_1_i_var37         (<connected-to-varset_1_i_var37>),         //         .i_var37
		.varset_1_i_var38         (<connected-to-varset_1_i_var38>),         //         .i_var38
		.varset_1_i_var39         (<connected-to-varset_1_i_var39>),         //         .i_var39
		.varset_1_i_var40         (<connected-to-varset_1_i_var40>),         //         .i_var40
		.varset_1_i_var41         (<connected-to-varset_1_i_var41>),         //         .i_var41
		.varset_1_i_var42         (<connected-to-varset_1_i_var42>),         //         .i_var42
		.varset_1_i_var43         (<connected-to-varset_1_i_var43>),         //         .i_var43
		.varset_1_i_var44         (<connected-to-varset_1_i_var44>),         //         .i_var44
		.varset_1_i_var45         (<connected-to-varset_1_i_var45>),         //         .i_var45
		.varset_1_i_var46         (<connected-to-varset_1_i_var46>),         //         .i_var46
		.varset_1_i_var47         (<connected-to-varset_1_i_var47>),         //         .i_var47
		.varset_1_i_var48         (<connected-to-varset_1_i_var48>),         //         .i_var48
		.varset_1_i_var49         (<connected-to-varset_1_i_var49>),         //         .i_var49
		.varset_1_i_var50         (<connected-to-varset_1_i_var50>),         //         .i_var50
		.varset_1_i_var51         (<connected-to-varset_1_i_var51>),         //         .i_var51
		.varset_1_i_var52         (<connected-to-varset_1_i_var52>),         //         .i_var52
		.varset_1_i_var53         (<connected-to-varset_1_i_var53>),         //         .i_var53
		.varset_1_i_var54         (<connected-to-varset_1_i_var54>),         //         .i_var54
		.varset_1_i_var55         (<connected-to-varset_1_i_var55>),         //         .i_var55
		.varset_1_i_var56         (<connected-to-varset_1_i_var56>),         //         .i_var56
		.varset_1_i_var57         (<connected-to-varset_1_i_var57>),         //         .i_var57
		.varset_1_i_var58         (<connected-to-varset_1_i_var58>),         //         .i_var58
		.varset_1_i_var59         (<connected-to-varset_1_i_var59>),         //         .i_var59
		.varset_1_o_reg0          (<connected-to-varset_1_o_reg0>),          //         .o_reg0
		.varset_1_o_reg1          (<connected-to-varset_1_o_reg1>),          //         .o_reg1
		.varset_1_o_reg2          (<connected-to-varset_1_o_reg2>),          //         .o_reg2
		.varset_1_o_reg3          (<connected-to-varset_1_o_reg3>),          //         .o_reg3
		.varset_1_o_reg4          (<connected-to-varset_1_o_reg4>),          //         .o_reg4
		.varset_1_o_reg5          (<connected-to-varset_1_o_reg5>),          //         .o_reg5
		.varset_1_o_reg6          (<connected-to-varset_1_o_reg6>),          //         .o_reg6
		.varset_1_o_reg7          (<connected-to-varset_1_o_reg7>),          //         .o_reg7
		.varset_1_o_reg8          (<connected-to-varset_1_o_reg8>),          //         .o_reg8
		.varset_1_o_reg9          (<connected-to-varset_1_o_reg9>),          //         .o_reg9
		.varset_1_o_reg10         (<connected-to-varset_1_o_reg10>),         //         .o_reg10
		.varset_1_o_reg11         (<connected-to-varset_1_o_reg11>),         //         .o_reg11
		.varset_1_o_reg12         (<connected-to-varset_1_o_reg12>),         //         .o_reg12
		.varset_1_o_reg13         (<connected-to-varset_1_o_reg13>),         //         .o_reg13
		.varset_1_o_reg14         (<connected-to-varset_1_o_reg14>),         //         .o_reg14
		.varset_1_o_reg15         (<connected-to-varset_1_o_reg15>),         //         .o_reg15
		.varset_1_o_reg16         (<connected-to-varset_1_o_reg16>),         //         .o_reg16
		.varset_1_o_reg17         (<connected-to-varset_1_o_reg17>),         //         .o_reg17
		.varset_1_o_reg18         (<connected-to-varset_1_o_reg18>),         //         .o_reg18
		.varset_1_o_reg19         (<connected-to-varset_1_o_reg19>),         //         .o_reg19
		.varset_1_o_reg20         (<connected-to-varset_1_o_reg20>),         //         .o_reg20
		.varset_1_o_reg21         (<connected-to-varset_1_o_reg21>),         //         .o_reg21
		.varset_1_o_reg22         (<connected-to-varset_1_o_reg22>),         //         .o_reg22
		.varset_1_o_reg23         (<connected-to-varset_1_o_reg23>),         //         .o_reg23
		.varset_1_o_reg24         (<connected-to-varset_1_o_reg24>),         //         .o_reg24
		.varset_1_o_reg25         (<connected-to-varset_1_o_reg25>),         //         .o_reg25
		.varset_1_o_reg26         (<connected-to-varset_1_o_reg26>),         //         .o_reg26
		.varset_1_o_reg27         (<connected-to-varset_1_o_reg27>),         //         .o_reg27
		.varset_1_o_reg28         (<connected-to-varset_1_o_reg28>),         //         .o_reg28
		.varset_1_o_reg29         (<connected-to-varset_1_o_reg29>),         //         .o_reg29
		.varset_1_o_reg30         (<connected-to-varset_1_o_reg30>),         //         .o_reg30
		.varset_1_o_reg31         (<connected-to-varset_1_o_reg31>),         //         .o_reg31
		.varset_1_o_reg32         (<connected-to-varset_1_o_reg32>),         //         .o_reg32
		.varset_1_o_reg33         (<connected-to-varset_1_o_reg33>),         //         .o_reg33
		.varset_1_o_reg34         (<connected-to-varset_1_o_reg34>),         //         .o_reg34
		.varset_1_o_reg35         (<connected-to-varset_1_o_reg35>),         //         .o_reg35
		.varset_1_o_reg36         (<connected-to-varset_1_o_reg36>),         //         .o_reg36
		.varset_1_o_reg37         (<connected-to-varset_1_o_reg37>),         //         .o_reg37
		.varset_1_o_reg38         (<connected-to-varset_1_o_reg38>),         //         .o_reg38
		.varset_1_o_reg39         (<connected-to-varset_1_o_reg39>),         //         .o_reg39
		.varset_1_o_reg40         (<connected-to-varset_1_o_reg40>),         //         .o_reg40
		.varset_1_o_reg41         (<connected-to-varset_1_o_reg41>),         //         .o_reg41
		.varset_1_o_reg42         (<connected-to-varset_1_o_reg42>),         //         .o_reg42
		.varset_1_o_reg43         (<connected-to-varset_1_o_reg43>),         //         .o_reg43
		.varset_1_o_reg44         (<connected-to-varset_1_o_reg44>),         //         .o_reg44
		.varset_1_o_reg45         (<connected-to-varset_1_o_reg45>),         //         .o_reg45
		.varset_1_o_reg46         (<connected-to-varset_1_o_reg46>),         //         .o_reg46
		.varset_1_o_reg47         (<connected-to-varset_1_o_reg47>),         //         .o_reg47
		.varset_1_o_reg48         (<connected-to-varset_1_o_reg48>),         //         .o_reg48
		.varset_1_o_reg49         (<connected-to-varset_1_o_reg49>),         //         .o_reg49
		.varset_1_o_reg50         (<connected-to-varset_1_o_reg50>),         //         .o_reg50
		.varset_1_o_reg51         (<connected-to-varset_1_o_reg51>),         //         .o_reg51
		.varset_1_o_reg52         (<connected-to-varset_1_o_reg52>),         //         .o_reg52
		.varset_1_o_reg53         (<connected-to-varset_1_o_reg53>),         //         .o_reg53
		.varset_1_o_reg54         (<connected-to-varset_1_o_reg54>),         //         .o_reg54
		.varset_1_o_reg55         (<connected-to-varset_1_o_reg55>),         //         .o_reg55
		.varset_1_o_reg56         (<connected-to-varset_1_o_reg56>),         //         .o_reg56
		.varset_1_o_reg57         (<connected-to-varset_1_o_reg57>),         //         .o_reg57
		.varset_1_o_reg58         (<connected-to-varset_1_o_reg58>),         //         .o_reg58
		.varset_1_o_reg59         (<connected-to-varset_1_o_reg59>),         //         .o_reg59
		.varset_1_o_latch_trigger (<connected-to-varset_1_o_latch_trigger>)  //         .o_latch_trigger
	);

